version: '3.8'

services:
  app:
    build: .
    container_name: go-app
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASS: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: testdb
    ports:
      - "8081:8080"
    networks:
      - backend

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
